spring:
  datasource:
    url: jdbc:h2:mem:witinerarydb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

weather:
  api:
    key: @weather.api.key@
    url: @weather.api.url@

server:
  address: localhost
  port: 8080